// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package bar represents the imported interface "hayride:wit-examples/bar@0.0.1".
package bar

import (
	"go.bytecodealliance.org/cm"
)

// Bar represents the imported resource "hayride:wit-examples/bar@0.0.1#bar".
//
//	resource bar
type Bar cm.Resource

// ResourceDrop represents the imported resource-drop for resource "bar".
//
// Drops a resource handle.
//
//go:nosplit
func (self Bar) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_BarResourceDrop((uint32)(self0))
	return
}

// NewBar represents the imported constructor for resource "bar".
//
//	constructor()
//
//go:nosplit
func NewBar() (result Bar) {
	result0 := wasmimport_NewBar()
	result = cm.Reinterpret[Bar]((uint32)(result0))
	return
}

// Bun represents the imported method "bun".
//
//	bun: func() -> string
//
//go:nosplit
func (self Bar) Bun() (result string) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_BarBun((uint32)(self0), &result)
	return
}
