// Code generated by wit-bindgen-go. DO NOT EDIT.

package bar

// This file contains wasmimport and wasmexport declarations for "hayride:wit-examples@0.0.1".

//go:wasmimport hayride:wit-examples/bar@0.0.1 [resource-drop]bar
//go:noescape
func wasmimport_BarResourceDrop(self0 uint32)

//go:wasmimport hayride:wit-examples/bar@0.0.1 [constructor]bar
//go:noescape
func wasmimport_NewBar() (result0 uint32)

//go:wasmimport hayride:wit-examples/bar@0.0.1 [method]bar.bun
//go:noescape
func wasmimport_BarBun(self0 uint32, result *string)
