// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package foobar represents the imported interface "hayride:wit-examples/foobar@0.0.1".
package foobar

import (
	"github.com/hayride-dev/wit-examples/internal/imports/hayride/wit-examples/bar"
	"go.bytecodealliance.org/cm"
)

// Bar represents the imported type alias "hayride:wit-examples/foobar@0.0.1#bar".
//
// See [bar.Bar] for more information.
type Bar = bar.Bar

// Foo represents the imported resource "hayride:wit-examples/foobar@0.0.1#foo".
//
//	resource foo
type Foo cm.Resource

// ResourceDrop represents the imported resource-drop for resource "foo".
//
// Drops a resource handle.
//
//go:nosplit
func (self Foo) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_FooResourceDrop((uint32)(self0))
	return
}

// NewFoo represents the imported constructor for resource "foo".
//
//	constructor()
//
//go:nosplit
func NewFoo() (result Foo) {
	result0 := wasmimport_NewFoo()
	result = cm.Reinterpret[Foo]((uint32)(result0))
	return
}

// Fun represents the imported method "fun".
//
//	fun: func() -> string
//
//go:nosplit
func (self Foo) Fun() (result string) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_FooFun((uint32)(self0), &result)
	return
}

// Foobar represents the imported function "foobar".
//
//	foobar: func(b: bar, f: foo) -> string
//
//go:nosplit
func Foobar(b Bar, f Foo) (result string) {
	b0 := cm.Reinterpret[uint32](b)
	f0 := cm.Reinterpret[uint32](f)
	wasmimport_Foobar((uint32)(b0), (uint32)(f0), &result)
	return
}
