package hayride:wit-examples@0.0.1;


interface bar {
    resource bar {
        constructor();
        bun: func() -> string;
    }
}

interface foobar {
    use bar.{bar};

    resource foo {
        constructor();
        fun: func() -> string;
    }

    foobar: func(b: bar, f: foo) -> string;
}

// foobar implementation:
// 

world exports {
    include hayride:wasip2/imports@0.0.51;

    export bar;
    export foobar;
}

world imports {
    include hayride:wasip2/imports@0.0.51;

    import bar;
    import foobar;

    include hayride:wasip2/exports@0.0.51;
}
