// Code generated by wit-bindgen-go. DO NOT EDIT.

package foo

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "hayride:wit-examples/foo@0.0.1".
var Exports struct {
	// Foo represents the caller-defined exports for resource "hayride:wit-examples/foo@0.0.1#foo".
	Foo struct {
		// Destructor represents the caller-defined, exported destructor for resource "foo".
		//
		// Resource destructor.
		Destructor func(self cm.Rep)

		// Foo represents the caller-defined, exported method "foo".
		//
		//	foo: func() -> string
		Foo func(self cm.Rep) (result string)
	}
}
