// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package bar represents the exported interface "hayride:wit-examples/bar@0.0.1".
package bar

import (
	"go.bytecodealliance.org/cm"
)

// Bar represents the exported resource "hayride:wit-examples/bar@0.0.1#bar".
//
//	resource bar
type Bar cm.Resource

// BarResourceNew represents the imported resource-new for resource "bar".
//
// Creates a new resource handle.
//
//go:nosplit
func BarResourceNew(rep cm.Rep) (result Bar) {
	rep0 := cm.Reinterpret[uint32](rep)
	result0 := wasmimport_BarResourceNew((uint32)(rep0))
	result = cm.Reinterpret[Bar]((uint32)(result0))
	return
}

// ResourceRep represents the imported resource-rep for resource "bar".
//
// Returns the underlying resource representation.
//
//go:nosplit
func (self Bar) ResourceRep() (result cm.Rep) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_BarResourceRep((uint32)(self0))
	result = cm.Reinterpret[cm.Rep]((uint32)(result0))
	return
}

// ResourceDrop represents the imported resource-drop for resource "bar".
//
// Drops a resource handle.
//
//go:nosplit
func (self Bar) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_BarResourceDrop((uint32)(self0))
	return
}

func init() {
	Exports.Bar.Destructor = func(self cm.Rep) {}
}
