// Code generated by wit-bindgen-go. DO NOT EDIT.

package bar

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "hayride:wit-examples/bar@0.0.1".
var Exports struct {
	// Bar represents the caller-defined exports for resource "hayride:wit-examples/bar@0.0.1#bar".
	Bar struct {
		// Destructor represents the caller-defined, exported destructor for resource "bar".
		//
		// Resource destructor.
		Destructor func(self cm.Rep)

		// Bar represents the caller-defined, exported method "bar".
		//
		//	bar: func() -> string
		Bar func(self cm.Rep) (result string)
	}
}
