// Code generated by wit-bindgen-go. DO NOT EDIT.

package bar

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "hayride:wit-examples@0.0.1".

//go:wasmimport [export]hayride:wit-examples/bar@0.0.1 [resource-new]bar
//go:noescape
func wasmimport_BarResourceNew(rep0 uint32) (result0 uint32)

//go:wasmimport [export]hayride:wit-examples/bar@0.0.1 [resource-rep]bar
//go:noescape
func wasmimport_BarResourceRep(self0 uint32) (result0 uint32)

//go:wasmimport [export]hayride:wit-examples/bar@0.0.1 [resource-drop]bar
//go:noescape
func wasmimport_BarResourceDrop(self0 uint32)

//go:wasmexport hayride:wit-examples/bar@0.0.1#[dtor]bar
//export hayride:wit-examples/bar@0.0.1#[dtor]bar
func wasmexport_BarDestructor(self0 uint32) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	Exports.Bar.Destructor(self)
	return
}

//go:wasmexport hayride:wit-examples/bar@0.0.1#[constructor]bar
//export hayride:wit-examples/bar@0.0.1#[constructor]bar
func wasmexport_Constructor() (result0 uint32) {
	result := Exports.Bar.Constructor()
	result0 = cm.Reinterpret[uint32](result)
	return
}

//go:wasmexport hayride:wit-examples/bar@0.0.1#[method]bar.bun
//export hayride:wit-examples/bar@0.0.1#[method]bar.bun
func wasmexport_BarBun(self0 uint32) (result *string) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	result_ := Exports.Bar.Bun(self)
	result = &result_
	return
}
