// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package foobar represents the exported interface "hayride:wit-examples/foobar@0.0.1".
package foobar

import (
	"github.com/hayride-dev/wit-examples/internal/hayride/wit-examples/bar"
	"github.com/hayride-dev/wit-examples/internal/hayride/wit-examples/foo"
)

// Foo represents the exported type alias "hayride:wit-examples/foobar@0.0.1#foo".
//
// See [foo.Foo] for more information.
type Foo = foo.Foo

// Bar represents the exported type alias "hayride:wit-examples/foobar@0.0.1#bar".
//
// See [bar.Bar] for more information.
type Bar = bar.Bar
