// Code generated by wit-bindgen-go. DO NOT EDIT.

package foobar

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "hayride:wit-examples@0.0.1".

//go:wasmexport hayride:wit-examples/foobar@0.0.1#foobar
//export hayride:wit-examples/foobar@0.0.1#foobar
func wasmexport_Foobar(bar0 uint32, foo0 uint32) (result *string) {
	bar_ := cm.Reinterpret[Bar]((uint32)(bar0))
	foo_ := cm.Reinterpret[Foo]((uint32)(foo0))
	result_ := Exports.Foobar(bar_, foo_)
	result = &result_
	return
}
