// Code generated by wit-bindgen-go. DO NOT EDIT.

package foobar

// Exports represents the caller-defined exports from "hayride:wit-examples/foobar@0.0.1".
var Exports struct {
	// Foobar represents the caller-defined, exported function "foobar".
	//
	//	foobar: func(bar: bar, foo: foo) -> string
	Foobar func(bar_ Bar, foo_ Foo) (result string)
}
