// Code generated by wit-bindgen-go. DO NOT EDIT.

package foobar

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "hayride:wit-examples@0.0.1".

//go:wasmimport [export]hayride:wit-examples/foobar@0.0.1 [resource-new]foo
//go:noescape
func wasmimport_FooResourceNew(rep0 uint32) (result0 uint32)

//go:wasmimport [export]hayride:wit-examples/foobar@0.0.1 [resource-rep]foo
//go:noescape
func wasmimport_FooResourceRep(self0 uint32) (result0 uint32)

//go:wasmimport [export]hayride:wit-examples/foobar@0.0.1 [resource-drop]foo
//go:noescape
func wasmimport_FooResourceDrop(self0 uint32)

//go:wasmexport hayride:wit-examples/foobar@0.0.1#[dtor]foo
//export hayride:wit-examples/foobar@0.0.1#[dtor]foo
func wasmexport_FooDestructor(self0 uint32) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	Exports.Foo.Destructor(self)
	return
}

//go:wasmexport hayride:wit-examples/foobar@0.0.1#[constructor]foo
//export hayride:wit-examples/foobar@0.0.1#[constructor]foo
func wasmexport_Constructor() (result0 uint32) {
	result := Exports.Foo.Constructor()
	result0 = cm.Reinterpret[uint32](result)
	return
}

//go:wasmexport hayride:wit-examples/foobar@0.0.1#[method]foo.fun
//export hayride:wit-examples/foobar@0.0.1#[method]foo.fun
func wasmexport_FooFun(self0 uint32) (result *string) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	result_ := Exports.Foo.Fun(self)
	result = &result_
	return
}

//go:wasmexport hayride:wit-examples/foobar@0.0.1#foobar
//export hayride:wit-examples/foobar@0.0.1#foobar
func wasmexport_Foobar(b0 uint32, f0 uint32) (result *string) {
	b := cm.Reinterpret[Bar]((uint32)(b0))
	f := cm.Reinterpret[Foo]((uint32)(f0))
	result_ := Exports.Foobar(b, f)
	result = &result_
	return
}
