// Code generated by wit-bindgen-go. DO NOT EDIT.

package foobar

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "hayride:wit-examples@0.0.1".

//go:wasmexport hayride:wit-examples/foobar@0.0.1#foobar
//export hayride:wit-examples/foobar@0.0.1#foobar
func wasmexport_Foobar(b0 uint32, f0 uint32) (result *string) {
	b := cm.Reinterpret[Bar]((uint32)(b0))
	f := cm.Reinterpret[Foo]((uint32)(f0))
	result_ := Exports.Foobar(b, f)
	result = &result_
	return
}
